spring:
  application:
    name: gateway service
  #profiles:
   # active: dev
  jackson:
    serialization:
      indent_output: true
      fail-on-empty-beans: false

  datasource:
      url: jdbc:mysql://localhost:3306/gatewaydb
      username: root
      password: Gracedube@80
      driver-class-name: com.mysql.jdbc.Driver
  jpa:
      database-platform: org.hibernate.dialect.MySQL8Dialect
      generate-ddl: true
      hibernate:
        ddl-auto: update
logging:
  level:
    ROOT: INFO
    zw.co.nbs.registrar: DEBUG
    org.springframework.web: info
    org.springframework.web.filter.CommonsRequestLoggingFilter: INFO
  config: classpath:logback-spring.xml
  # DEVTOOLS (DevToolsProperties)
spring.devtools.add-properties: true
spring.devtools.livereload.enabled: true
spring.devtools.livereload.port: 35729
server:
  port: 8284
  error:
    path: /error
  tomcat:
    threads:
      max: 20
basic:
  user:
    username: gsc
    password: gsc@2024?
    role: USER
api:
  title: Gateway Service Charges
  description: Gateway Service Charges API
  contact:
    name: NBS Information Technology
  licence:
    text: Licence
  swagger:
    version: 1.0.0
    path-selector-regex: /api.*
---
spring:
  profiles: staging
  cloud:
    config:
      uri: http://192.168.1.123:30001, http://192.168.1.133:30001
---
spring:
  profiles: prod
  cloud:
    config:
      uri: http://192.168.1.133:30001, http://192.168.1.123:30001

